table orders
	lineageTag: ba5a943a-2c8d-48ef-8d6f-3f1cd3bd9d96

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 1dd791c0-e04a-4902-8680-6a30ac4d0eac
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 96c1d8f3-afdf-4c53-81a4-38c1fa985c49
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: df7b1876-4d11-4757-aade-af7870b05431
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 722b1a34-763b-4b21-9932-ef4a39b79ac6
			defaultHierarchy: LocalDateTable_c648f750-2373-4c0f-b3c5-5caa2e3692c5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ea4b9545-8134-417e-804b-d74007870df5
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: a7c58ab9-bca9-4e0b-a85b-f54268fd9a41
			defaultHierarchy: LocalDateTable_32dbeb79-4176-433f-83d4-16ee73156ed9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: fd286c48-d372-4453-82ab-8a695ddf909b
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 85a5e079-faa5-4f2b-8e8f-ce5966df86ca
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: a879481f-b1ae-4b1a-b3f0-8861d8692d65
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: a74cabb1-0d37-4603-b04a-b66a04df22a6
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: ceb3ae03-e408-461e-b6f9-095fa3312432
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: baf32cc3-b080-4e3e-8642-8c0b548e9a8d
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 4c96dfb8-5682-43a4-aa4a-88310bb00b2b
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: c830d0e8-cea9-4693-bbe9-9446dec5e3dd
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6378ff32-96c7-4624-ab1d-02263b5ef2a1
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 06a046fd-b686-4930-8f13-35153ee38f22
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9b35bc62-7079-4fa5-b4aa-29319b52b1b7
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 3ecbdc78-733f-4b74-bbfc-9ecf29f5ee13
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 6fcf5675-423d-48a2-a1e9-f309d2f9a92c
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: eeef48a0-9a23-401b-8ea5-edc73616a8f5
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 13a83d50-c8b0-453d-90f4-108e297407f6
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: int64
		formatString: 0
		lineageTag: 77e92a20-6dd5-45cd-88fa-da2d9d01dc0f
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		lineageTag: bf12fda9-f10f-44c0-82fa-df07c51589fb
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\DataScience&AI\PowerBI\orders.xlsx"), null, true),
				    orders_Sheet = Source{[Item="orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", Int64.Type}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

